import jsPDF from 'jspdf';

interface SummaryPdfData {
  title: string;
  summary: string;
  keyPoints: string[];
  mainIdeas: string[];
  length: string;
  originalFileName?: string;
}

export function exportSummaryToPdf(data: SummaryPdfData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let yPos = 20;

  // Header Banner Background
  doc.setFillColor(15, 23, 42); // Dark slate bg
  doc.rect(0, 0, pageWidth, 28, 'F');

  // Header Title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('DOCUS AI', margin, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text('Document Summary & Analytics Report', margin, 21);

  // Date Tag
  const dateStr = new Date().toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
  doc.text(dateStr, pageWidth - margin, 21, { align: 'right' });

  yPos = 36;

  // Document Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  const titleLines = doc.splitTextToSize(data.title, contentWidth);
  doc.text(titleLines, margin, yPos);
  yPos += titleLines.length * 6 + 4;

  // Metadata Pill
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, yPos, 45, 7, 2, 2, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text(`DETAIL LEVEL: ${data.length}`, margin + 4, yPos + 4.8);
  yPos += 12;

  // Section 1: Executive Summary
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text('EXECUTIVE SUMMARY', margin, yPos);
  yPos += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(51, 65, 85);
  const summaryLines = doc.splitTextToSize(data.summary, contentWidth);
  
  // Page overflow check helper
  const checkPageBreak = (neededHeight: number) => {
    if (yPos + neededHeight > 280) {
      doc.addPage();
      yPos = 20;
    }
  };

  checkPageBreak(summaryLines.length * 5);
  doc.text(summaryLines, margin, yPos);
  yPos += summaryLines.length * 5 + 8;

  // Section 2: Key Takeaways
  if (data.keyPoints && data.keyPoints.length > 0) {
    checkPageBreak(15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.text('KEY TAKEAWAYS', margin, yPos);
    yPos += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85);

    for (const point of data.keyPoints) {
      const bulletLines = doc.splitTextToSize(`• ${point}`, contentWidth - 4);
      checkPageBreak(bulletLines.length * 5 + 2);
      doc.text(bulletLines, margin + 2, yPos);
      yPos += bulletLines.length * 5 + 2;
    }
    yPos += 6;
  }

  // Section 3: Core Main Ideas
  if (data.mainIdeas && data.mainIdeas.length > 0) {
    checkPageBreak(15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.text('CORE CONCEPTS & THEMES', margin, yPos);
    yPos += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85);

    for (const idea of data.mainIdeas) {
      const ideaLines = doc.splitTextToSize(`▪ ${idea}`, contentWidth - 4);
      checkPageBreak(ideaLines.length * 5 + 2);
      doc.text(ideaLines, margin + 2, yPos);
      yPos += ideaLines.length * 5 + 2;
    }
  }

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, 285, pageWidth - margin, 285);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by DOCUS AI Document Assistant', margin, 290);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, 290, { align: 'right' });
  }

  const safeFileName = (data.title || 'summary')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_')
    .substring(0, 30);

  doc.save(`${safeFileName}_docus_summary.pdf`);
}
