[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"
  NETLIFY_NEXT_FORCE_ADMIN_FETCH = "true"
  NEXT_USE_NETLIFY_EDGE = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["tesseract.js", "pdf-to-png-converter", "@aws-sdk/client-textract", "pg", "@prisma/client", "pdf-parse"]
